language: node_js
node_js:
  - '9'
addons:
  ssh_known_hosts: $DEPLOY_HOST_STAGING
install:
  - npm install
before_script:
  - npm run build
script:
  - npm run lint
before_deploy:
  - openssl aes-256-cbc -K $encrypted_dac4fb374c68_key -iv $encrypted_dac4fb374c68_iv -in id_travis.enc -out ~\/.ssh/id_travis -d
deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -avrcq --delete-after --exclude /public $TRAVIS_BUILD_DIR/dist $DEPLOY_USER_STAGING@$DEPLOY_HOST_STAGING:/home/pibase/html/tf-staging.pascal-iske.de/public
    on:
      branch: preview/staging
